#!/usr/bin/env bash

exec java -server -XX:+HeapDumpOnOutOfMemoryError -Xmx512m -classpath 'lib/*' -Dlog4j.configurationFile=conf/log4j2.xml -Dcamdash.configurationDir=conf com.alexhilman.cameradashboard.ui.App
